import { Platform } from 'quasar'

interface CordovaPlugins {
  permissions: PermissionPlugin
}
const plugins = Platform.is.cordova
  ? (cordova.plugins as CordovaPlugins)
  : undefined

type ACCESS_CHECKIN_PROPERTIES = 'android.permission.ACCESS_CHECKIN_PROPERTIES'
type ACCESS_COARSE_LOCATION = 'android.permission.ACCESS_COARSE_LOCATION'
type ACCESS_FINE_LOCATION = 'android.permission.ACCESS_FINE_LOCATION'
type ACCESS_LOCATION_EXTRA_COMMANDS = 'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS'
type ACCESS_MOCK_LOCATION = 'android.permission.ACCESS_MOCK_LOCATION'
type ACCESS_NETWORK_STATE = 'android.permission.ACCESS_NETWORK_STATE'
type ACCESS_SURFACE_FLINGER = 'android.permission.ACCESS_SURFACE_FLINGER'
type ACCESS_WIFI_STATE = 'android.permission.ACCESS_WIFI_STATE'
type ACCOUNT_MANAGER = 'android.permission.ACCOUNT_MANAGER'
type ADD_VOICEMAIL = 'com.android.voicemail.permission.ADD_VOICEMAIL'
type AUTHENTICATE_ACCOUNTS = 'android.permission.AUTHENTICATE_ACCOUNTS'
type BATTERY_STATS = 'android.permission.BATTERY_STATS'
type BIND_ACCESSIBILITY_SERVICE = 'android.permission.BIND_ACCESSIBILITY_SERVICE'
type BIND_APPWIDGET = 'android.permission.BIND_APPWIDGET'
type BIND_CARRIER_MESSAGING_SERVICE = 'android.permission.BIND_CARRIER_MESSAGING_SERVICE'
type BIND_DEVICE_ADMIN = 'android.permission.BIND_DEVICE_ADMIN'
type BIND_DREAM_SERVICE = 'android.permission.BIND_DREAM_SERVICE'
type BIND_INPUT_METHOD = 'android.permission.BIND_INPUT_METHOD'
type BIND_NFC_SERVICE = 'android.permission.BIND_NFC_SERVICE'
type BIND_NOTIFICATION_LISTENER_SERVICE = 'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE'
type BIND_PRINT_SERVICE = 'android.permission.BIND_PRINT_SERVICE'
type BIND_REMOTEVIEWS = 'android.permission.BIND_REMOTEVIEWS'
type BIND_TEXT_SERVICE = 'android.permission.BIND_TEXT_SERVICE'
type BIND_TV_INPUT = 'android.permission.BIND_TV_INPUT'
type BIND_VOICE_INTERACTION = 'android.permission.BIND_VOICE_INTERACTION'
type BIND_VPN_SERVICE = 'android.permission.BIND_VPN_SERVICE'
type BIND_WALLPAPER = 'android.permission.BIND_WALLPAPER'
type BLUETOOTH = 'android.permission.BLUETOOTH'
type BLUETOOTH_ADMIN = 'android.permission.BLUETOOTH_ADMIN'
type BLUETOOTH_PRIVILEGED = 'android.permission.BLUETOOTH_PRIVILEGED'
type BODY_SENSORS = 'android.permission.BODY_SENSORS'
type BRICK = 'android.permission.BRICK'
type BROADCAST_PACKAGE_REMOVED = 'android.permission.BROADCAST_PACKAGE_REMOVED'
type BROADCAST_SMS = 'android.permission.BROADCAST_SMS'
type BROADCAST_STICKY = 'android.permission.BROADCAST_STICKY'
type BROADCAST_WAP_PUSH = 'android.permission.BROADCAST_WAP_PUSH'
type CALL_PHONE = 'android.permission.CALL_PHONE'
type CALL_PRIVILEGED = 'android.permission.CALL_PRIVILEGED'
type CAMERA = 'android.permission.CAMERA'
type CAPTURE_AUDIO_OUTPUT = 'android.permission.CAPTURE_AUDIO_OUTPUT'
type CAPTURE_SECURE_VIDEO_OUTPUT = 'android.permission.CAPTURE_SECURE_VIDEO_OUTPUT'
type CAPTURE_VIDEO_OUTPUT = 'android.permission.CAPTURE_VIDEO_OUTPUT'
type CHANGE_COMPONENT_ENABLED_STATE = 'android.permission.CHANGE_COMPONENT_ENABLED_STATE'
type CHANGE_CONFIGURATION = 'android.permission.CHANGE_CONFIGURATION'
type CHANGE_NETWORK_STATE = 'android.permission.CHANGE_NETWORK_STATE'
type CHANGE_WIFI_MULTICAST_STATE = 'android.permission.CHANGE_WIFI_MULTICAST_STATE'
type CHANGE_WIFI_STATE = 'android.permission.CHANGE_WIFI_STATE'
type CLEAR_APP_CACHE = 'android.permission.CLEAR_APP_CACHE'
type CLEAR_APP_USER_DATA = 'android.permission.CLEAR_APP_USER_DATA'
type CONTROL_LOCATION_UPDATES = 'android.permission.CONTROL_LOCATION_UPDATES'
type DELETE_CACHE_FILES = 'android.permission.DELETE_CACHE_FILES'
type DELETE_PACKAGES = 'android.permission.DELETE_PACKAGES'
type DEVICE_POWER = 'android.permission.DEVICE_POWER'
type DIAGNOSTIC = 'android.permission.DIAGNOSTIC'
type DISABLE_KEYGUARD = 'android.permission.DISABLE_KEYGUARD'
type DUMP = 'android.permission.DUMP'
type EXPAND_STATUS_BAR = 'android.permission.EXPAND_STATUS_BAR'
type FACTORY_TEST = 'android.permission.FACTORY_TEST'
type FLASHLIGHT = 'android.permission.FLASHLIGHT'
type FORCE_BACK = 'android.permission.FORCE_BACK'
type GET_ACCOUNTS = 'android.permission.GET_ACCOUNTS'
type GET_PACKAGE_SIZE = 'android.permission.GET_PACKAGE_SIZE'
type GET_TASKS = 'android.permission.GET_TASKS'
type GET_TOP_ACTIVITY_INFO = 'android.permission.GET_TOP_ACTIVITY_INFO'
type GLOBAL_SEARCH = 'android.permission.GLOBAL_SEARCH'
type HARDWARE_TEST = 'android.permission.HARDWARE_TEST'
type INJECT_EVENTS = 'android.permission.INJECT_EVENTS'
type INSTALL_LOCATION_PROVIDER = 'android.permission.INSTALL_LOCATION_PROVIDER'
type INSTALL_PACKAGES = 'android.permission.INSTALL_PACKAGES'
type INSTALL_SHORTCUT = 'com.android.launcher.permission.INSTALL_SHORTCUT'
type INTERNAL_SYSTEM_WINDOW = 'android.permission.INTERNAL_SYSTEM_WINDOW'
type INTERNET = 'android.permission.INTERNET'
type KILL_BACKGROUND_PROCESSES = 'android.permission.KILL_BACKGROUND_PROCESSES'
type LOCATION_HARDWARE = 'android.permission.LOCATION_HARDWARE'
type MANAGE_ACCOUNTS = 'android.permission.MANAGE_ACCOUNTS'
type MANAGE_APP_TOKENS = 'android.permission.MANAGE_APP_TOKENS'
type MANAGE_DOCUMENTS = 'android.permission.MANAGE_DOCUMENTS'
type MASTER_CLEAR = 'android.permission.MASTER_CLEAR'
type MEDIA_CONTENT_CONTROL = 'android.permission.MEDIA_CONTENT_CONTROL'
type MODIFY_AUDIO_SETTINGS = 'android.permission.MODIFY_AUDIO_SETTINGS'
type MODIFY_PHONE_STATE = 'android.permission.MODIFY_PHONE_STATE'
type MOUNT_FORMAT_FILESYSTEMS = 'android.permission.MOUNT_FORMAT_FILESYSTEMS'
type MOUNT_UNMOUNT_FILESYSTEMS = 'android.permission.MOUNT_UNMOUNT_FILESYSTEMS'
type NFC = 'android.permission.NFC'
type PERSISTENT_ACTIVITY = 'android.permission.PERSISTENT_ACTIVITY'
type PROCESS_OUTGOING_CALLS = 'android.permission.PROCESS_OUTGOING_CALLS'
type READ_CALENDAR = 'android.permission.READ_CALENDAR'
type READ_CALL_LOG = 'android.permission.READ_CALL_LOG'
type READ_CONTACTS = 'android.permission.READ_CONTACTS'
type READ_EXTERNAL_STORAGE = 'android.permission.READ_EXTERNAL_STORAGE'
type READ_FRAME_BUFFER = 'android.permission.READ_FRAME_BUFFER'
type READ_HISTORY_BOOKMARKS = 'com.android.browser.permission.READ_HISTORY_BOOKMARKS'
type READ_INPUT_STATE = 'android.permission.READ_INPUT_STATE'
type READ_LOGS = 'android.permission.READ_LOGS'
type READ_PHONE_STATE = 'android.permission.READ_PHONE_STATE'
type READ_PROFILE = 'android.permission.READ_PROFILE'
type READ_SMS = 'android.permission.READ_SMS'
type READ_SOCIAL_STREAM = 'android.permission.READ_SOCIAL_STREAM'
type READ_SYNC_SETTINGS = 'android.permission.READ_SYNC_SETTINGS'
type READ_SYNC_STATS = 'android.permission.READ_SYNC_STATS'
type READ_USER_DICTIONARY = 'android.permission.READ_USER_DICTIONARY'
type READ_VOICEMAIL = 'com.android.voicemail.permission.READ_VOICEMAIL'
type REBOOT = 'android.permission.REBOOT'
type RECEIVE_BOOT_COMPLETED = 'android.permission.RECEIVE_BOOT_COMPLETED'
type RECEIVE_MMS = 'android.permission.RECEIVE_MMS'
type RECEIVE_SMS = 'android.permission.RECEIVE_SMS'
type RECEIVE_WAP_PUSH = 'android.permission.RECEIVE_WAP_PUSH'
type RECORD_AUDIO = 'android.permission.RECORD_AUDIO'
type REORDER_TASKS = 'android.permission.REORDER_TASKS'
type RESTART_PACKAGES = 'android.permission.RESTART_PACKAGES'
type SEND_RESPOND_VIA_MESSAGE = 'android.permission.SEND_RESPOND_VIA_MESSAGE'
type SEND_SMS = 'android.permission.SEND_SMS'
type SET_ACTIVITY_WATCHER = 'android.permission.SET_ACTIVITY_WATCHER'
type SET_ALARM = 'com.android.alarm.permission.SET_ALARM'
type SET_ALWAYS_FINISH = 'android.permission.SET_ALWAYS_FINISH'
type SET_ANIMATION_SCALE = 'android.permission.SET_ANIMATION_SCALE'
type SET_DEBUG_APP = 'android.permission.SET_DEBUG_APP'
type SET_ORIENTATION = 'android.permission.SET_ORIENTATION'
type SET_POINTER_SPEED = 'android.permission.SET_POINTER_SPEED'
type SET_PREFERRED_APPLICATIONS = 'android.permission.SET_PREFERRED_APPLICATIONS'
type SET_PROCESS_LIMIT = 'android.permission.SET_PROCESS_LIMIT'
type SET_TIME = 'android.permission.SET_TIME'
type SET_TIME_ZONE = 'android.permission.SET_TIME_ZONE'
type SET_WALLPAPER = 'android.permission.SET_WALLPAPER'
type SET_WALLPAPER_HINTS = 'android.permission.SET_WALLPAPER_HINTS'
type SIGNAL_PERSISTENT_PROCESSES = 'android.permission.SIGNAL_PERSISTENT_PROCESSES'
type STATUS_BAR = 'android.permission.STATUS_BAR'
type SUBSCRIBED_FEEDS_READ = 'android.permission.SUBSCRIBED_FEEDS_READ'
type SUBSCRIBED_FEEDS_WRITE = 'android.permission.SUBSCRIBED_FEEDS_WRITE'
type SYSTEM_ALERT_WINDOW = 'android.permission.SYSTEM_ALERT_WINDOW'
type TRANSMIT_IR = 'android.permission.TRANSMIT_IR'
type UNINSTALL_SHORTCUT = 'com.android.launcher.permission.UNINSTALL_SHORTCUT'
type UPDATE_DEVICE_STATS = 'android.permission.UPDATE_DEVICE_STATS'
type USE_CREDENTIALS = 'android.permission.USE_CREDENTIALS'
type USE_SIP = 'android.permission.USE_SIP'
type VIBRATE = 'android.permission.VIBRATE'
type WAKE_LOCK = 'android.permission.WAKE_LOCK'
type WRITE_APN_SETTINGS = 'android.permission.WRITE_APN_SETTINGS'
type WRITE_CALENDAR = 'android.permission.WRITE_CALENDAR'
type WRITE_CALL_LOG = 'android.permission.WRITE_CALL_LOG'
type WRITE_CONTACTS = 'android.permission.WRITE_CONTACTS'
type WRITE_EXTERNAL_STORAGE = 'android.permission.WRITE_EXTERNAL_STORAGE'
type WRITE_GSERVICES = 'android.permission.WRITE_GSERVICES'
type WRITE_HISTORY_BOOKMARKS = 'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS'
type WRITE_PROFILE = 'android.permission.WRITE_PROFILE'
type WRITE_SECURE_SETTINGS = 'android.permission.WRITE_SECURE_SETTINGS'
type WRITE_SETTINGS = 'android.permission.WRITE_SETTINGS'
type WRITE_SMS = 'android.permission.WRITE_SMS'
type WRITE_SOCIAL_STREAM = 'android.permission.WRITE_SOCIAL_STREAM'
type WRITE_SYNC_SETTINGS = 'android.permission.WRITE_SYNC_SETTINGS'
type WRITE_USER_DICTIONARY = 'android.permission.WRITE_USER_DICTIONARY'
type WRITE_VOICEMAIL = 'com.android.voicemail.permission.WRITE_VOICEMAIL'
type Permission =
  | ACCESS_CHECKIN_PROPERTIES
  | ACCESS_COARSE_LOCATION
  | ACCESS_FINE_LOCATION
  | ACCESS_LOCATION_EXTRA_COMMANDS
  | ACCESS_MOCK_LOCATION
  | ACCESS_NETWORK_STATE
  | ACCESS_SURFACE_FLINGER
  | ACCESS_WIFI_STATE
  | ACCOUNT_MANAGER
  | ADD_VOICEMAIL
  | AUTHENTICATE_ACCOUNTS
  | BATTERY_STATS
  | BIND_ACCESSIBILITY_SERVICE
  | BIND_APPWIDGET
  | BIND_CARRIER_MESSAGING_SERVICE
  | BIND_DEVICE_ADMIN
  | BIND_DREAM_SERVICE
  | BIND_INPUT_METHOD
  | BIND_NFC_SERVICE
  | BIND_NOTIFICATION_LISTENER_SERVICE
  | BIND_PRINT_SERVICE
  | BIND_REMOTEVIEWS
  | BIND_TEXT_SERVICE
  | BIND_TV_INPUT
  | BIND_VOICE_INTERACTION
  | BIND_VPN_SERVICE
  | BIND_WALLPAPER
  | BLUETOOTH
  | BLUETOOTH_ADMIN
  | BLUETOOTH_PRIVILEGED
  | BODY_SENSORS
  | BRICK
  | BROADCAST_PACKAGE_REMOVED
  | BROADCAST_SMS
  | BROADCAST_STICKY
  | BROADCAST_WAP_PUSH
  | CALL_PHONE
  | CALL_PRIVILEGED
  | CAMERA
  | CAPTURE_AUDIO_OUTPUT
  | CAPTURE_SECURE_VIDEO_OUTPUT
  | CAPTURE_VIDEO_OUTPUT
  | CHANGE_COMPONENT_ENABLED_STATE
  | CHANGE_CONFIGURATION
  | CHANGE_NETWORK_STATE
  | CHANGE_WIFI_MULTICAST_STATE
  | CHANGE_WIFI_STATE
  | CLEAR_APP_CACHE
  | CLEAR_APP_USER_DATA
  | CONTROL_LOCATION_UPDATES
  | DELETE_CACHE_FILES
  | DELETE_PACKAGES
  | DEVICE_POWER
  | DIAGNOSTIC
  | DISABLE_KEYGUARD
  | DUMP
  | EXPAND_STATUS_BAR
  | FACTORY_TEST
  | FLASHLIGHT
  | FORCE_BACK
  | GET_ACCOUNTS
  | GET_PACKAGE_SIZE
  | GET_TASKS
  | GET_TOP_ACTIVITY_INFO
  | GLOBAL_SEARCH
  | HARDWARE_TEST
  | INJECT_EVENTS
  | INSTALL_LOCATION_PROVIDER
  | INSTALL_PACKAGES
  | INSTALL_SHORTCUT
  | INTERNAL_SYSTEM_WINDOW
  | INTERNET
  | KILL_BACKGROUND_PROCESSES
  | LOCATION_HARDWARE
  | MANAGE_ACCOUNTS
  | MANAGE_APP_TOKENS
  | MANAGE_DOCUMENTS
  | MASTER_CLEAR
  | MEDIA_CONTENT_CONTROL
  | MODIFY_AUDIO_SETTINGS
  | MODIFY_PHONE_STATE
  | MOUNT_FORMAT_FILESYSTEMS
  | MOUNT_UNMOUNT_FILESYSTEMS
  | NFC
  | PERSISTENT_ACTIVITY
  | PROCESS_OUTGOING_CALLS
  | READ_CALENDAR
  | READ_CALL_LOG
  | READ_CONTACTS
  | READ_EXTERNAL_STORAGE
  | READ_FRAME_BUFFER
  | READ_HISTORY_BOOKMARKS
  | READ_INPUT_STATE
  | READ_LOGS
  | READ_PHONE_STATE
  | READ_PROFILE
  | READ_SMS
  | READ_SOCIAL_STREAM
  | READ_SYNC_SETTINGS
  | READ_SYNC_STATS
  | READ_USER_DICTIONARY
  | READ_VOICEMAIL
  | REBOOT
  | RECEIVE_BOOT_COMPLETED
  | RECEIVE_MMS
  | RECEIVE_SMS
  | RECEIVE_WAP_PUSH
  | RECORD_AUDIO
  | REORDER_TASKS
  | RESTART_PACKAGES
  | SEND_RESPOND_VIA_MESSAGE
  | SEND_SMS
  | SET_ACTIVITY_WATCHER
  | SET_ALARM
  | SET_ALWAYS_FINISH
  | SET_ANIMATION_SCALE
  | SET_DEBUG_APP
  | SET_ORIENTATION
  | SET_POINTER_SPEED
  | SET_PREFERRED_APPLICATIONS
  | SET_PROCESS_LIMIT
  | SET_TIME
  | SET_TIME_ZONE
  | SET_WALLPAPER
  | SET_WALLPAPER_HINTS
  | SIGNAL_PERSISTENT_PROCESSES
  | STATUS_BAR
  | SUBSCRIBED_FEEDS_READ
  | SUBSCRIBED_FEEDS_WRITE
  | SYSTEM_ALERT_WINDOW
  | TRANSMIT_IR
  | UNINSTALL_SHORTCUT
  | UPDATE_DEVICE_STATS
  | USE_CREDENTIALS
  | USE_SIP
  | VIBRATE
  | WAKE_LOCK
  | WRITE_APN_SETTINGS
  | WRITE_CALENDAR
  | WRITE_CALL_LOG
  | WRITE_CONTACTS
  | WRITE_EXTERNAL_STORAGE
  | WRITE_GSERVICES
  | WRITE_HISTORY_BOOKMARKS
  | WRITE_PROFILE
  | WRITE_SECURE_SETTINGS
  | WRITE_SETTINGS
  | WRITE_SMS
  | WRITE_SOCIAL_STREAM
  | WRITE_SYNC_SETTINGS
  | WRITE_USER_DICTIONARY
  | WRITE_VOICEMAIL

type Permissions = Permission | Permission[]
interface PermissionPlugin {
  ACCESS_CHECKIN_PROPERTIES: ACCESS_CHECKIN_PROPERTIES
  ACCESS_COARSE_LOCATION: ACCESS_COARSE_LOCATION
  ACCESS_FINE_LOCATION: ACCESS_FINE_LOCATION
  ACCESS_LOCATION_EXTRA_COMMANDS: ACCESS_LOCATION_EXTRA_COMMANDS
  ACCESS_MOCK_LOCATION: ACCESS_MOCK_LOCATION
  ACCESS_NETWORK_STATE: ACCESS_NETWORK_STATE
  ACCESS_SURFACE_FLINGER: ACCESS_SURFACE_FLINGER
  ACCESS_WIFI_STATE: ACCESS_WIFI_STATE
  ACCOUNT_MANAGER: ACCOUNT_MANAGER
  ADD_VOICEMAIL: ADD_VOICEMAIL
  AUTHENTICATE_ACCOUNTS: AUTHENTICATE_ACCOUNTS
  BATTERY_STATS: BATTERY_STATS
  BIND_ACCESSIBILITY_SERVICE: BIND_ACCESSIBILITY_SERVICE
  BIND_APPWIDGET: BIND_APPWIDGET
  BIND_CARRIER_MESSAGING_SERVICE: BIND_CARRIER_MESSAGING_SERVICE
  BIND_DEVICE_ADMIN: BIND_DEVICE_ADMIN
  BIND_DREAM_SERVICE: BIND_DREAM_SERVICE
  BIND_INPUT_METHOD: BIND_INPUT_METHOD
  BIND_NFC_SERVICE: BIND_NFC_SERVICE
  BIND_NOTIFICATION_LISTENER_SERVICE: BIND_NOTIFICATION_LISTENER_SERVICE
  BIND_PRINT_SERVICE: BIND_PRINT_SERVICE
  BIND_REMOTEVIEWS: BIND_REMOTEVIEWS
  BIND_TEXT_SERVICE: BIND_TEXT_SERVICE
  BIND_TV_INPUT: BIND_TV_INPUT
  BIND_VOICE_INTERACTION: BIND_VOICE_INTERACTION
  BIND_VPN_SERVICE: BIND_VPN_SERVICE
  BIND_WALLPAPER: BIND_WALLPAPER
  BLUETOOTH: BLUETOOTH
  BLUETOOTH_ADMIN: BLUETOOTH_ADMIN
  BLUETOOTH_PRIVILEGED: BLUETOOTH_PRIVILEGED
  BODY_SENSORS: BODY_SENSORS
  BRICK: BRICK
  BROADCAST_PACKAGE_REMOVED: BROADCAST_PACKAGE_REMOVED
  BROADCAST_SMS: BROADCAST_SMS
  BROADCAST_STICKY: BROADCAST_STICKY
  BROADCAST_WAP_PUSH: BROADCAST_WAP_PUSH
  CALL_PHONE: CALL_PHONE
  CALL_PRIVILEGED: CALL_PRIVILEGED
  CAMERA: CAMERA
  CAPTURE_AUDIO_OUTPUT: CAPTURE_AUDIO_OUTPUT
  CAPTURE_SECURE_VIDEO_OUTPUT: CAPTURE_SECURE_VIDEO_OUTPUT
  CAPTURE_VIDEO_OUTPUT: CAPTURE_VIDEO_OUTPUT
  CHANGE_COMPONENT_ENABLED_STATE: CHANGE_COMPONENT_ENABLED_STATE
  CHANGE_CONFIGURATION: CHANGE_CONFIGURATION
  CHANGE_NETWORK_STATE: CHANGE_NETWORK_STATE
  CHANGE_WIFI_MULTICAST_STATE: CHANGE_WIFI_MULTICAST_STATE
  CHANGE_WIFI_STATE: CHANGE_WIFI_STATE
  CLEAR_APP_CACHE: CLEAR_APP_CACHE
  CLEAR_APP_USER_DATA: CLEAR_APP_USER_DATA
  CONTROL_LOCATION_UPDATES: CONTROL_LOCATION_UPDATES
  DELETE_CACHE_FILES: DELETE_CACHE_FILES
  DELETE_PACKAGES: DELETE_PACKAGES
  DEVICE_POWER: DEVICE_POWER
  DIAGNOSTIC: DIAGNOSTIC
  DISABLE_KEYGUARD: DISABLE_KEYGUARD
  DUMP: DUMP
  EXPAND_STATUS_BAR: EXPAND_STATUS_BAR
  FACTORY_TEST: FACTORY_TEST
  FLASHLIGHT: FLASHLIGHT
  FORCE_BACK: FORCE_BACK
  GET_ACCOUNTS: GET_ACCOUNTS
  GET_PACKAGE_SIZE: GET_PACKAGE_SIZE
  GET_TASKS: GET_TASKS
  GET_TOP_ACTIVITY_INFO: GET_TOP_ACTIVITY_INFO
  GLOBAL_SEARCH: GLOBAL_SEARCH
  HARDWARE_TEST: HARDWARE_TEST
  INJECT_EVENTS: INJECT_EVENTS
  INSTALL_LOCATION_PROVIDER: INSTALL_LOCATION_PROVIDER
  INSTALL_PACKAGES: INSTALL_PACKAGES
  INSTALL_SHORTCUT: INSTALL_SHORTCUT
  INTERNAL_SYSTEM_WINDOW: INTERNAL_SYSTEM_WINDOW
  INTERNET: INTERNET
  KILL_BACKGROUND_PROCESSES: KILL_BACKGROUND_PROCESSES
  LOCATION_HARDWARE: LOCATION_HARDWARE
  MANAGE_ACCOUNTS: MANAGE_ACCOUNTS
  MANAGE_APP_TOKENS: MANAGE_APP_TOKENS
  MANAGE_DOCUMENTS: MANAGE_DOCUMENTS
  MASTER_CLEAR: MASTER_CLEAR
  MEDIA_CONTENT_CONTROL: MEDIA_CONTENT_CONTROL
  MODIFY_AUDIO_SETTINGS: MODIFY_AUDIO_SETTINGS
  MODIFY_PHONE_STATE: MODIFY_PHONE_STATE
  MOUNT_FORMAT_FILESYSTEMS: MOUNT_FORMAT_FILESYSTEMS
  MOUNT_UNMOUNT_FILESYSTEMS: MOUNT_UNMOUNT_FILESYSTEMS
  NFC: NFC
  PERSISTENT_ACTIVITY: PERSISTENT_ACTIVITY
  PROCESS_OUTGOING_CALLS: PROCESS_OUTGOING_CALLS
  READ_CALENDAR: READ_CALENDAR
  READ_CALL_LOG: READ_CALL_LOG
  READ_CONTACTS: READ_CONTACTS
  READ_EXTERNAL_STORAGE: READ_EXTERNAL_STORAGE
  READ_FRAME_BUFFER: READ_FRAME_BUFFER
  READ_HISTORY_BOOKMARKS: READ_HISTORY_BOOKMARKS
  READ_INPUT_STATE: READ_INPUT_STATE
  READ_LOGS: READ_LOGS
  READ_PHONE_STATE: READ_PHONE_STATE
  READ_PROFILE: READ_PROFILE
  READ_SMS: READ_SMS
  READ_SOCIAL_STREAM: READ_SOCIAL_STREAM
  READ_SYNC_SETTINGS: READ_SYNC_SETTINGS
  READ_SYNC_STATS: READ_SYNC_STATS
  READ_USER_DICTIONARY: READ_USER_DICTIONARY
  READ_VOICEMAIL: READ_VOICEMAIL
  REBOOT: REBOOT
  RECEIVE_BOOT_COMPLETED: RECEIVE_BOOT_COMPLETED
  RECEIVE_MMS: RECEIVE_MMS
  RECEIVE_SMS: RECEIVE_SMS
  RECEIVE_WAP_PUSH: RECEIVE_WAP_PUSH
  RECORD_AUDIO: RECORD_AUDIO
  REORDER_TASKS: REORDER_TASKS
  RESTART_PACKAGES: RESTART_PACKAGES
  SEND_RESPOND_VIA_MESSAGE: SEND_RESPOND_VIA_MESSAGE
  SEND_SMS: SEND_SMS
  SET_ACTIVITY_WATCHER: SET_ACTIVITY_WATCHER
  SET_ALARM: SET_ALARM
  SET_ALWAYS_FINISH: SET_ALWAYS_FINISH
  SET_ANIMATION_SCALE: SET_ANIMATION_SCALE
  SET_DEBUG_APP: SET_DEBUG_APP
  SET_ORIENTATION: SET_ORIENTATION
  SET_POINTER_SPEED: SET_POINTER_SPEED
  SET_PREFERRED_APPLICATIONS: SET_PREFERRED_APPLICATIONS
  SET_PROCESS_LIMIT: SET_PROCESS_LIMIT
  SET_TIME: SET_TIME
  SET_TIME_ZONE: SET_TIME_ZONE
  SET_WALLPAPER: SET_WALLPAPER
  SET_WALLPAPER_HINTS: SET_WALLPAPER_HINTS
  SIGNAL_PERSISTENT_PROCESSES: SIGNAL_PERSISTENT_PROCESSES
  STATUS_BAR: STATUS_BAR
  SUBSCRIBED_FEEDS_READ: SUBSCRIBED_FEEDS_READ
  SUBSCRIBED_FEEDS_WRITE: SUBSCRIBED_FEEDS_WRITE
  SYSTEM_ALERT_WINDOW: SYSTEM_ALERT_WINDOW
  TRANSMIT_IR: TRANSMIT_IR
  UNINSTALL_SHORTCUT: UNINSTALL_SHORTCUT
  UPDATE_DEVICE_STATS: UPDATE_DEVICE_STATS
  USE_CREDENTIALS: USE_CREDENTIALS
  USE_SIP: USE_SIP
  VIBRATE: VIBRATE
  WAKE_LOCK: WAKE_LOCK
  WRITE_APN_SETTINGS: WRITE_APN_SETTINGS
  WRITE_CALENDAR: WRITE_CALENDAR
  WRITE_CALL_LOG: WRITE_CALL_LOG
  WRITE_CONTACTS: WRITE_CONTACTS
  WRITE_EXTERNAL_STORAGE: WRITE_EXTERNAL_STORAGE
  WRITE_GSERVICES: WRITE_GSERVICES
  WRITE_HISTORY_BOOKMARKS: WRITE_HISTORY_BOOKMARKS
  WRITE_PROFILE: WRITE_PROFILE
  WRITE_SECURE_SETTINGS: WRITE_SECURE_SETTINGS
  WRITE_SETTINGS: WRITE_SETTINGS
  WRITE_SMS: WRITE_SMS
  WRITE_SOCIAL_STREAM: WRITE_SOCIAL_STREAM
  WRITE_SYNC_SETTINGS: WRITE_SYNC_SETTINGS
  WRITE_USER_DICTIONARY: WRITE_USER_DICTIONARY
  WRITE_VOICEMAIL: WRITE_VOICEMAIL
  checkPermission: (
    permission: Permissions,
    successCallback: Function,
    errorCallback: Function
  ) => void
  requestPermission: (
    permission: Permissions,
    successCallback: Function,
    errorCallback: Function
  ) => void
  requestPermissions: (
    permission: Permissions,
    successCallback: Function,
    errorCallback: Function
  ) => void
}

export default plugins?.permissions
